import Head from "next/head";
import Footer from "../components/footer";
import { HeaderBar } from "../components/headerbar";
import Banner from "../components/banner";
import Seletes from "../components/selete";
import Body from "../components/body";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title className="font-kh">ទំព័រដើម</title>
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <HeaderBar />
        <Banner />
        <Seletes />
        <Body/>
      </main>
      {/* <Footer /> */}
    </>
  );
}
