import Navbar from "./navBar/navbar";
import Footer from "./footer/footer";
import Head from "next/head";

export default function Layout({ children, title, session }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="./logo.png" />
      </Head>
      <Navbar session={session} />
      <main className="min-h-screen content">{children}</main>
      <Footer />
    </>
  );
}
